{
 "title": "Demo PocketMoney",
 "time": { "from": "now-20y", "to": "now" },
 "templating": {
  "list": [
   { "name": "hidden", "label": "Hidden Accounts", "query": "hidden : 1,shown : 0" },
   { "name": "database", "label": "Database", "query": "pocketmoney-transactions" }
  ]
 },
 "panels": [
  {
   "title": "Sum per category",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    data#>>'{category,name}' AS category,\n    SUM((data->'amount')::float) AS amount\nFROM \"${database:sql}\"\nWHERE to_timestamp((data#>>'{transaction,date}'), 'YYYY-MM-DD') BETWEEN $__timeFrom() AND $__timeTo() AND (data#>'{transaction,account,hidden}')::int IN (${hidden:sql})\nGROUP BY category"
    }
   ]
  },
  {
   "title": "Account Stats",
   "type": "table",
   "gridPos": { "h": 23, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    data#>>'{transaction,account,name}' AS Name,\n    SUM((data->'amount')::float) AS Balance,\n    COUNT(data)::int AS TX\nFROM \"${database:sql}\"\nWHERE to_timestamp((data#>>'{transaction,date}'), 'YYYY-MM-DD') BETWEEN $__timeFrom() AND $__timeTo() AND (data#>'{transaction,account,hidden}')::int IN (${hidden:sql})\nGROUP BY Name"
    }
   ]
  },
  {
   "title": "Category Stats",
   "type": "table",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    data#>>'{category,name}' AS Name,\n    SUM((data->'amount')::float) AS Amount,\n    COUNT((data->'amount')::float) AS TX\nFROM \"${database:sql}\"\nWHERE to_timestamp((data#>>'{transaction,date}'), 'YYYY-MM-DD') BETWEEN $__timeFrom() AND $__timeTo() AND (data#>'{transaction,account,hidden}')::int IN (${hidden:sql})\nGROUP BY Name"
    }
   ]
  },
  {
   "title": "Daily Amount",
   "type": "barchart",
   "gridPos": { "h": 23, "w": 11, "x": 11, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('day', to_timestamp((data#>>'{transaction,date}'), 'YYYY-MM-DD')) AS time,\n    SUM((data->'amount')::float) AS Amount\nFROM \"${database:sql}\"\nWHERE to_timestamp((data#>>'{transaction,date}'), 'YYYY-MM-DD') BETWEEN $__timeFrom() AND $__timeTo() AND (data#>'{transaction,account,hidden}')::int IN (${hidden:sql})\nGROUP BY time"
    }
   ]
  }
 ]
}